### ISSUE TITLE
Show Materials

### ISSUE THREAD

**Issue by mzks** [mzks/pfsTest#3]
When I run geantino, i wanna check materials.
What should I do?

**Comment by pn11** [comment]
これも以下のようにすればできるのでは

https://github.com/mzks/pfsTest/issues/4#issuecomment-269425039

**Comment by mzks** [comment]
verbose levelをあげても表示するオプションはありません。
簡単にはLogical volume 名が見えるので、それで判断するので十分といえば十分です。
簡単で無くていいのであればverboseを継承してMyVerbose classを作ればLogical volumeを持っているので実装は可能だと思います。
